#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'
require 'bundler/cli'

root        = File.expand_path('../..', __FILE__)
destination = root + '/tmp'

ENV['GEM_HOME']    = destination
ENV['GEM_PATH']    = destination
ENV['BUNDLE_PATH'] = destination

Bundler::CLI.start ['install', "--gemfile=#{root}/Gemfile", destination]

Bundler.setup :default, :test

require 'rspec/core'
success = RSpec::Core::Runner.run(['--color', root + '/spec'], $stderr, $stdout)

exit! success ? 0 : 1 
